const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('ferro', {
  versions: () => ipcRenderer.invoke('ferro:versions'),
  instances: () => ipcRenderer.invoke('ferro:instances'),
  createInstance: (data) => ipcRenderer.invoke('ferro:createInstance', data),
  fabricLoaders: (mcVersion) => ipcRenderer.invoke('ferro:fabricLoaders', mcVersion),
  loaders: (data) => ipcRenderer.invoke('ferro:loaders', data),
  modSearch: (data) => ipcRenderer.invoke('ferro:modSearch', data),
  mods: (data) => ipcRenderer.invoke('ferro:mods', data),
  modInstall: (data) => ipcRenderer.invoke('ferro:modInstall', data),
  modRemove: (data) => ipcRenderer.invoke('ferro:modRemove', data),
  modToggle: (data) => ipcRenderer.invoke('ferro:modToggle', data),
  modUpdates: (data) => ipcRenderer.invoke('ferro:modUpdates', data),
  modUpdate: (data) => ipcRenderer.invoke('ferro:modUpdate', data),
  packSearch: (data) => ipcRenderer.invoke('ferro:packSearch', data),
  packVersions: (data) => ipcRenderer.invoke('ferro:packVersions', data),
  packInstall: (data) => ipcRenderer.invoke('ferro:packInstall', data),
  clientId: () => ipcRenderer.invoke('ferro:clientId'),
  discord: () => ipcRenderer.invoke('ferro:discord'),
  setDiscord: (data) => ipcRenderer.invoke('ferro:setDiscord', data),
  setClientId: (data) => ipcRenderer.invoke('ferro:setClientId', data),
  authStatus: () => ipcRenderer.invoke('ferro:authStatus'),
  authStart: () => ipcRenderer.invoke('ferro:authStart'),
  authPoll: (data) => ipcRenderer.invoke('ferro:authPoll', data),
  authLogout: () => ipcRenderer.invoke('ferro:authLogout'),
  accounts: () => ipcRenderer.invoke('ferro:accounts'),
  authSelect: (data) => ipcRenderer.invoke('ferro:authSelect', data),
  authRemove: (data) => ipcRenderer.invoke('ferro:authRemove', data),
  authBrowser: () => ipcRenderer.invoke('ferro:authBrowser'),
  authWindow: () => ipcRenderer.invoke('ferro:authWindow'),
  authBrowserCancel: () => ipcRenderer.invoke('ferro:authBrowserCancel'),
  authWindowCancel: () => ipcRenderer.invoke('ferro:authWindowCancel'),
  appVersion: () => ipcRenderer.invoke('ferro:appVersion'),
  checkUpdate: () => ipcRenderer.invoke('ferro:checkUpdate'),
  quitAndInstall: () => ipcRenderer.invoke('ferro:quitAndInstall'),
  onUpdate: (cb) => ipcRenderer.on('ferro:update', (_, d) => cb(d)),
  onShown: (cb) => ipcRenderer.once('ferro:shown', () => cb()),
  onSettled: (cb) => ipcRenderer.once('ferro:settled', () => cb()),
  skin: (data) => ipcRenderer.invoke('ferro:skin', data),
  skinApply: (data) => ipcRenderer.invoke('ferro:skinApply', data),
  skinReset: () => ipcRenderer.invoke('ferro:skinReset'),
  exportInstance: (data) => ipcRenderer.invoke('ferro:exportInstance', data),
  importInstance: () => ipcRenderer.invoke('ferro:importInstance'),
  backups: (data) => ipcRenderer.invoke('ferro:backups', data),
  backupCreate: (data) => ipcRenderer.invoke('ferro:backupCreate', data),
  backupRestore: (data) => ipcRenderer.invoke('ferro:backupRestore', data),
  backupDelete: (data) => ipcRenderer.invoke('ferro:backupDelete', data),
  crashes: (data) => ipcRenderer.invoke('ferro:crashes', data),
  crashRead: (data) => ipcRenderer.invoke('ferro:crashRead', data),
  openCrashes: (data) => ipcRenderer.invoke('ferro:openCrashes', data),
  onAuthResult: (cb) => {
    ipcRenderer.on('ferro:auth-done', (_, d) => cb(null, d));
    ipcRenderer.on('ferro:auth-error', (_, e) => cb(e, null));
  },
  java: () => ipcRenderer.invoke('ferro:java'),
  launch: (data) => ipcRenderer.invoke('ferro:launch', data),
  stop: () => ipcRenderer.invoke('ferro:stop'),
  status: () => ipcRenderer.invoke('ferro:status'),
  nameCheck: (data) => ipcRenderer.invoke('ferro:nameCheck', data),
  nameSuggest: (data) => ipcRenderer.invoke('ferro:nameSuggest', data),
  updateSettings: (data) => ipcRenderer.invoke('ferro:updateSettings', data),
  openFolder: (data) => ipcRenderer.invoke('ferro:openFolder', data),
  duplicateInstance: (data) => ipcRenderer.invoke('ferro:duplicateInstance', data),
  deleteInstance: (data) => ipcRenderer.invoke('ferro:deleteInstance', data),
  renameInstance: (data) => ipcRenderer.invoke('ferro:renameInstance', data),
  onLog: (cb) => ipcRenderer.on('ferro:log', (_, t) => cb(t)),
});
